// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db_common

import (
	"database/sql"
	"time"
)

type Account struct {
	ID         int32         `json:"id"`
	Uuid       string        `json:"uuid"`
	WorldID    int32         `json:"world_id"`
	ProfileIdx sql.NullInt32 `json:"profile_idx"`
	CreatedAt  time.Time     `json:"created_at"`
}

type AccountUser struct {
	ID         int32     `json:"id"`
	AccountID  int32     `json:"account_id"`
	GameDb     int32     `json:"game_db"`
	Nickname   string    `json:"nickname"`
	SignedInAt time.Time `json:"signed_in_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type Sharding struct {
	ID     int32 `json:"id"`
	GameDb int32 `json:"game_db"`
	Count  int32 `json:"count"`
}

type Shop struct {
	ID      int32        `json:"id"`
	Type    int32        `json:"type"`
	Visible int32        `json:"visible"`
	Name    string       `json:"name"`
	Desc    string       `json:"desc"`
	StartAt sql.NullTime `json:"start_at"`
	EndAt   sql.NullTime `json:"end_at"`
}

type ShopCategory struct {
	ID      int32  `json:"id"`
	ShopID  int32  `json:"shop_id"`
	Visible int32  `json:"visible"`
	Name    string `json:"name"`
	Order   int32  `json:"order"`
}

type ShopGoods struct {
	ID             int32          `json:"id"`
	ShopCategoryID int32          `json:"shop_category_id"`
	Type           int32          `json:"type"`
	EnumID         string         `json:"enum_id"`
	Info           sql.NullString `json:"info"`
	Name           string         `json:"name"`
	Desc           string         `json:"desc"`
	CostType       int32          `json:"cost_type"`
	CostEnumID     string         `json:"cost_enum_id"`
	Cost           int32          `json:"cost"`
	OriginalCost   int32          `json:"original_cost"`
	Count          int32          `json:"count"`
	Visible        int32          `json:"visible"`
	StartAt        sql.NullTime   `json:"start_at"`
	EndAt          sql.NullTime   `json:"end_at"`
}
