// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db_battle

import (
	"database/sql"
	"time"
)

type BattleResult struct {
	ID                 int32        `json:"id"`
	AccountUserID      int32        `json:"account_user_id"`
	MatchAccountUserID int32        `json:"match_account_user_id"`
	ChannelID          string       `json:"channel_id"`
	DeckID             int32        `json:"deck_id"`
	Result             int32        `json:"result"`
	BattleStartAt      time.Time    `json:"battle_start_at"`
	ConfirmedAt        sql.NullTime `json:"confirmed_at"`
	CreatedAt          time.Time    `json:"created_at"`
}

type User struct {
	ID            int32     `json:"id"`
	AccountUserID int32     `json:"account_user_id"`
	MatchPoint    int32     `json:"match_point"`
	MatchWin      int32     `json:"match_win"`
	MatchLose     int32     `json:"match_lose"`
	CreatedAt     time.Time `json:"created_at"`
}
