// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db_game

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID            int32  `json:"id"`
	AccountUserID int32  `json:"account_user_id"`
	EnumID        string `json:"enum_id"`
	Type          int32  `json:"type"`
	Balance       int64  `json:"balance"`
}

type Character struct {
	ID             int32     `json:"id"`
	AccountUserID  int32     `json:"account_user_id"`
	EnumID         string    `json:"enum_id"`
	Exp            int32     `json:"exp"`
	EquipmentLevel int32     `json:"equipment_level"`
	CreatedAt      time.Time `json:"created_at"`
}

type CharacterBroadcast struct {
	ID              int32     `json:"id"`
	AccountUserID   int32     `json:"account_user_id"`
	CharacterEnumID string    `json:"character_enum_id"`
	TimelineEnumID  string    `json:"timeline_enum_id"`
	Type            int32     `json:"type"`
	OnAir           int32     `json:"on_air"`
	Complete        int32     `json:"complete"`
	BroadcastedAt   time.Time `json:"broadcasted_at"`
}

type CharacterCollection struct {
	ID              int32     `json:"id"`
	AccountUserID   int32     `json:"account_user_id"`
	CharacterEnumID string    `json:"character_enum_id"`
	AffectionExp    int32     `json:"affection_exp"`
	Count           int32     `json:"count"`
	CreatedAt       time.Time `json:"created_at"`
}

type Costume struct {
	ID              int32     `json:"id"`
	AccountUserID   int32     `json:"account_user_id"`
	EnumID          string    `json:"enum_id"`
	CharacterEnumID string    `json:"character_enum_id"`
	State           int32     `json:"state"`
	CreatedAt       time.Time `json:"created_at"`
}

type Deck struct {
	ID            int32         `json:"id"`
	AccountUserID int32         `json:"account_user_id"`
	Index         int32         `json:"index"`
	Name          string        `json:"name"`
	CharacterID0  sql.NullInt32 `json:"character_id_0"`
	CharacterID1  sql.NullInt32 `json:"character_id_1"`
	CharacterID2  sql.NullInt32 `json:"character_id_2"`
	CharacterID3  sql.NullInt32 `json:"character_id_3"`
	CharacterID4  sql.NullInt32 `json:"character_id_4"`
	CreatedAt     time.Time     `json:"created_at"`
}

type FateCard struct {
	ID              int32          `json:"id"`
	AccountUserID   int32          `json:"account_user_id"`
	EnumID          string         `json:"enum_id"`
	CharacterEnumID sql.NullString `json:"character_enum_id"`
	CreatedAt       time.Time      `json:"created_at"`
}

type GachaLog struct {
	ID              int64     `json:"id"`
	AccountUserID   int32     `json:"account_user_id"`
	EnumID          string    `json:"enum_id"`
	CharacterEnumID string    `json:"character_enum_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Item struct {
	ID            int32     `json:"id"`
	AccountUserID int32     `json:"account_user_id"`
	EnumID        string    `json:"enum_id"`
	Count         int32     `json:"count"`
	CreatedAt     time.Time `json:"created_at"`
}

type Mail struct {
	ID            int32          `json:"id"`
	AccountUserID int32          `json:"account_user_id"`
	Sender        string         `json:"sender"`
	Type          int32          `json:"type"`
	Status        int32          `json:"status"`
	DeleteAll     int32          `json:"delete_all"`
	Attachment    sql.NullString `json:"attachment"`
	Title         string         `json:"title"`
	Message       sql.NullString `json:"message"`
	ExpiredAt     sql.NullTime   `json:"expired_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

type User struct {
	ID               int32          `json:"id"`
	AccountUserID    int32          `json:"account_user_id"`
	StoryIndex       int32          `json:"story_index"`
	TutorialInfo     string         `json:"tutorial_info"`
	ShopInfo         sql.NullString `json:"shop_info"`
	DailyResetAt     time.Time      `json:"daily_reset_at"`
	BroadcastResetAt time.Time      `json:"broadcast_reset_at"`
	CreatedAt        time.Time      `json:"created_at"`
}
