// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: abyss.extension.sql

package db_static_data

import (
	"context"
)

const getAbyssByLevel = `-- name: GetAbyssByLevel :one
SELECT id, enum_id, level, map_file, size, size_x, size_y, rule, abyss_title_resource, boss, minor, elite, tower, time_limit, created_at FROM abyss WHERE ` + "`" + `level` + "`" + ` = ? LIMIT 1
`

func (q *Queries) GetAbyssByLevel(ctx context.Context, level int32) (Abyss, error) {
	row := q.db.QueryRowContext(ctx, getAbyssByLevel, level)
	var i Abyss
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.Level,
		&i.MapFile,
		&i.Size,
		&i.SizeX,
		&i.SizeY,
		&i.Rule,
		&i.AbyssTitleResource,
		&i.Boss,
		&i.Minor,
		&i.Elite,
		&i.Tower,
		&i.TimeLimit,
		&i.CreatedAt,
	)
	return i, err
}
