// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: asset.extension.sql

package db_static_data

import (
	"context"
)

const getAssetByAssetEnum = `-- name: GetAssetByAssetEnum :one
SELECT id, enum_id, ce_asset, ce_asset_grade, grade_resource_thumbnail, grade_resource, image_reference, pictogram_reference, grade_reference, image_tile, created_at FROM asset WHERE ce_asset = ? LIMIT 1
`

func (q *Queries) GetAssetByAssetEnum(ctx context.Context, ceAsset string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByAssetEnum, ceAsset)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.CeAsset,
		&i.CeAssetGrade,
		&i.GradeResourceThumbnail,
		&i.GradeResource,
		&i.ImageReference,
		&i.PictogramReference,
		&i.GradeReference,
		&i.ImageTile,
		&i.CreatedAt,
	)
	return i, err
}
