// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: character_resource.sql

package db_static_data

import (
	"context"
)

const getCharacterResourceByEnumId = `-- name: GetCharacterResourceByEnumId :one
SELECT id, enum_id, spine, eff_landing, character_weapon, phone_case_close, phone_case_open, day_ld_reference, night_ld_reference, night_sd_reference, portrait_night_reference, portrait_daytime_reference, thumbnail_reference, thumbnail_sd_reference, background_reference, card_reference, voice_skill, created_at FROM character_resource WHERE enum_id = ?
`

func (q *Queries) GetCharacterResourceByEnumId(ctx context.Context, enumID string) (CharacterResource, error) {
	row := q.db.QueryRowContext(ctx, getCharacterResourceByEnumId, enumID)
	var i CharacterResource
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.Spine,
		&i.EffLanding,
		&i.CharacterWeapon,
		&i.PhoneCaseClose,
		&i.PhoneCaseOpen,
		&i.DayLdReference,
		&i.NightLdReference,
		&i.NightSdReference,
		&i.PortraitNightReference,
		&i.PortraitDaytimeReference,
		&i.ThumbnailReference,
		&i.ThumbnailSdReference,
		&i.BackgroundReference,
		&i.CardReference,
		&i.VoiceSkill,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterResources = `-- name: GetCharacterResources :many
SELECT id, enum_id, spine, eff_landing, character_weapon, phone_case_close, phone_case_open, day_ld_reference, night_ld_reference, night_sd_reference, portrait_night_reference, portrait_daytime_reference, thumbnail_reference, thumbnail_sd_reference, background_reference, card_reference, voice_skill, created_at FROM character_resource
`

func (q *Queries) GetCharacterResources(ctx context.Context) ([]CharacterResource, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterResource{}
	for rows.Next() {
		var i CharacterResource
		if err := rows.Scan(
			&i.ID,
			&i.EnumID,
			&i.Spine,
			&i.EffLanding,
			&i.CharacterWeapon,
			&i.PhoneCaseClose,
			&i.PhoneCaseOpen,
			&i.DayLdReference,
			&i.NightLdReference,
			&i.NightSdReference,
			&i.PortraitNightReference,
			&i.PortraitDaytimeReference,
			&i.ThumbnailReference,
			&i.ThumbnailSdReference,
			&i.BackgroundReference,
			&i.CardReference,
			&i.VoiceSkill,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
