// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: character_costume_bundle.sql

package db_static_data

import (
	"context"
)

const getCharacterCostumeBundleByEnumId = `-- name: GetCharacterCostumeBundleByEnumId :one
SELECT id, enum_id, costume, created_at FROM ` + "`" + `character_costume_bundle` + "`" + ` WHERE enum_id = ?
`

func (q *Queries) GetCharacterCostumeBundleByEnumId(ctx context.Context, enumID string) (CharacterCostumeBundle, error) {
	row := q.db.QueryRowContext(ctx, getCharacterCostumeBundleByEnumId, enumID)
	var i CharacterCostumeBundle
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.Costume,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterCostumeBundleList = `-- name: GetCharacterCostumeBundleList :many
SELECT id, enum_id, costume, created_at FROM ` + "`" + `character_costume_bundle` + "`" + `
`

func (q *Queries) GetCharacterCostumeBundleList(ctx context.Context) ([]CharacterCostumeBundle, error) {
	rows, err := q.db.QueryContext(ctx, getCharacterCostumeBundleList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterCostumeBundle{}
	for rows.Next() {
		var i CharacterCostumeBundle
		if err := rows.Scan(
			&i.ID,
			&i.EnumID,
			&i.Costume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
