// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: gacha_pool_group.sql

package db_static_data

import (
	"context"
)

const getGachaPoolGroupByEnumId = `-- name: GetGachaPoolGroupByEnumId :one
SELECT id, enum_id, pool_condition, pool_id, pool_id_rate, created_at FROM ` + "`" + `gacha_pool_group` + "`" + ` WHERE enum_id = ?
`

func (q *Queries) GetGachaPoolGroupByEnumId(ctx context.Context, enumID string) (GachaPoolGroup, error) {
	row := q.db.QueryRowContext(ctx, getGachaPoolGroupByEnumId, enumID)
	var i GachaPoolGroup
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.PoolCondition,
		&i.PoolID,
		&i.PoolIDRate,
		&i.CreatedAt,
	)
	return i, err
}

const getGachaPoolGroupList = `-- name: GetGachaPoolGroupList :many
SELECT id, enum_id, pool_condition, pool_id, pool_id_rate, created_at FROM ` + "`" + `gacha_pool_group` + "`" + `
`

func (q *Queries) GetGachaPoolGroupList(ctx context.Context) ([]GachaPoolGroup, error) {
	rows, err := q.db.QueryContext(ctx, getGachaPoolGroupList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GachaPoolGroup{}
	for rows.Next() {
		var i GachaPoolGroup
		if err := rows.Scan(
			&i.ID,
			&i.EnumID,
			&i.PoolCondition,
			&i.PoolID,
			&i.PoolIDRate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
