// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: gacha_drop_a.sql

package db_static_data

import (
	"context"
)

const getGachaDropAByEnumId = `-- name: GetGachaDropAByEnumId :one
SELECT id, enum_id, drop_character, pool_id, created_at FROM ` + "`" + `gacha_drop_a` + "`" + ` WHERE enum_id = ?
`

func (q *Queries) GetGachaDropAByEnumId(ctx context.Context, enumID string) (GachaDropA, error) {
	row := q.db.QueryRowContext(ctx, getGachaDropAByEnumId, enumID)
	var i GachaDropA
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.DropCharacter,
		&i.PoolID,
		&i.CreatedAt,
	)
	return i, err
}

const getGachaDropAList = `-- name: GetGachaDropAList :many
SELECT id, enum_id, drop_character, pool_id, created_at FROM ` + "`" + `gacha_drop_a` + "`" + `
`

func (q *Queries) GetGachaDropAList(ctx context.Context) ([]GachaDropA, error) {
	rows, err := q.db.QueryContext(ctx, getGachaDropAList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GachaDropA{}
	for rows.Next() {
		var i GachaDropA
		if err := rows.Scan(
			&i.ID,
			&i.EnumID,
			&i.DropCharacter,
			&i.PoolID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
