// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: gacha_drop_c.sql

package db_static_data

import (
	"context"
)

const getGachaDropCByEnumId = `-- name: GetGachaDropCByEnumId :one
SELECT id, enum_id, drop_character, pool_id, created_at FROM ` + "`" + `gacha_drop_c` + "`" + ` WHERE enum_id = ?
`

func (q *Queries) GetGachaDropCByEnumId(ctx context.Context, enumID string) (GachaDropC, error) {
	row := q.db.QueryRowContext(ctx, getGachaDropCByEnumId, enumID)
	var i GachaDropC
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.DropCharacter,
		&i.PoolID,
		&i.CreatedAt,
	)
	return i, err
}

const getGachaDropCList = `-- name: GetGachaDropCList :many
SELECT id, enum_id, drop_character, pool_id, created_at FROM ` + "`" + `gacha_drop_c` + "`" + `
`

func (q *Queries) GetGachaDropCList(ctx context.Context) ([]GachaDropC, error) {
	rows, err := q.db.QueryContext(ctx, getGachaDropCList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GachaDropC{}
	for rows.Next() {
		var i GachaDropC
		if err := rows.Scan(
			&i.ID,
			&i.EnumID,
			&i.DropCharacter,
			&i.PoolID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
