// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: localization.sql

package db_static_data

import (
	"context"
)

const getLocalizationByEnumId = `-- name: GetLocalizationByEnumId :one
SELECT id, enum_id, kr, en, created_at FROM localization WHERE enum_id = ?
`

func (q *Queries) GetLocalizationByEnumId(ctx context.Context, enumID string) (Localization, error) {
	row := q.db.QueryRowContext(ctx, getLocalizationByEnumId, enumID)
	var i Localization
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.Kr,
		&i.En,
		&i.CreatedAt,
	)
	return i, err
}

const getLocalizations = `-- name: GetLocalizations :many
SELECT id, enum_id, kr, en, created_at FROM localization
`

func (q *Queries) GetLocalizations(ctx context.Context) ([]Localization, error) {
	rows, err := q.db.QueryContext(ctx, getLocalizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Localization{}
	for rows.Next() {
		var i Localization
		if err := rows.Scan(
			&i.ID,
			&i.EnumID,
			&i.Kr,
			&i.En,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
