// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: stargem_growth.sql

package db_static_data

import (
	"context"
)

const getStargemGrowthByEnumId = `-- name: GetStargemGrowthByEnumId :one
SELECT id, enum_id, level, exp, exp_plus, created_at FROM stargem_growth WHERE enum_id = ?
`

func (q *Queries) GetStargemGrowthByEnumId(ctx context.Context, enumID string) (StargemGrowth, error) {
	row := q.db.QueryRowContext(ctx, getStargemGrowthByEnumId, enumID)
	var i StargemGrowth
	err := row.Scan(
		&i.ID,
		&i.EnumID,
		&i.Level,
		&i.Exp,
		&i.ExpPlus,
		&i.CreatedAt,
	)
	return i, err
}

const getStargemGrowths = `-- name: GetStargemGrowths :many
SELECT id, enum_id, level, exp, exp_plus, created_at FROM stargem_growth
`

func (q *Queries) GetStargemGrowths(ctx context.Context) ([]StargemGrowth, error) {
	rows, err := q.db.QueryContext(ctx, getStargemGrowths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StargemGrowth{}
	for rows.Next() {
		var i StargemGrowth
		if err := rows.Scan(
			&i.ID,
			&i.EnumID,
			&i.Level,
			&i.Exp,
			&i.ExpPlus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
